bugsnag/bugsnag-unity-performance

- .github/ISSUE_TEMPLATE/A.md
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/support.md
Adding Unity performance issue templates.
> [SUP-3154] Automated adjustment of repository templates

- .buildkite/block.full.yml
- .buildkite/pipeline.full.yml
- .buildkite/pipeline.yml
- .buildkite/pipeline_trigger.sh
- features/fixtures/mazerunner/Packages/manifest.json
The ultimate goal for performance CI should be the following:
Always build the SDK package on Unity 2020
Normal CI Run:
All supported platforms built with Unity 2021
Full CI Run:
All supported platforms built with Unity 2020, 2021 and 2022.
This PR adds support for normal and full runs, and enables testing fixtures built with Unity 2020
> PLAT-10277 expand performance CI testing to unity 2020

- .buildkite/block.full.yml
- .buildkite/pipeline.full.yml
- .buildkite/pipeline.yml
- .buildkite/pipeline_trigger.sh
- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Internal/Version.cs
- CHANGELOG.md
- CONTRIBUTING.md
- features/fixtures/mazerunner/Assets/Scripts/Scenarios/Persistence/PValueRetry.cs
- features/fixtures/mazerunner/Packages/manifest.json
> Release v1.0.0

- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Enums/HttpVerb.cs
- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Enums/HttpVerb.cs.meta
- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Internal/SpanFactory.cs
- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Public/BugsnagPerformance.cs
- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Public/Span.cs
- CHANGELOG.md
- features/fixtures/mazerunner/Assets/Scenes/MainScene.unity
- features/fixtures/mazerunner/Assets/Scripts/Scenarios/Network/ManualNetworkSpan.cs
- features/fixtures/mazerunner/Assets/Scripts/Scenarios/Network/ManualNetworkSpan.cs.meta
- features/fixtures/mazerunner/Assets/Scripts/Scenarios/SceneLoad/ManualSceneSpan.cs
- features/fixtures/mazerunner/Assets/Scripts/Scenarios/SceneLoad/ManualSceneSpan.cs.meta
- features/network_spans.feature
- features/scene_load_spans.feature
add the following methods:
```
Span BugsnagPerformance.StartSceneSpan(string sceneName, SpanOptions spanOptions)
Span BugsnagPerformance.StartNetworkSpan(string url, HttpVerb verb, SpanOptions spanOptions)
Span.EndNetworkSpan(string statusCode, int requestContentLength, int responseContentLength)
```
Added new e2e tests
> PLAT-10770 add manual scene load and network request instrumentation

- .buildkite/pipeline.full.yml
- .buildkite/pipeline.yml
- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Internal/PersistentState.cs
- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Models/ResourceModel.cs
- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Native/WindowsNative.cs
- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Native/WindowsNative.cs.meta
- BugsnagPerformance/Assets/UnitTests/ResourceTests.cs
- BugsnagPerformance/Assets/UnitTests/ResourceTests.cs.meta
- Rakefile
- features/fixtures/mazerunner/Assets/Editor/Builder.cs
- features/fixtures/mazerunner/Assets/Editor/DisablingBitcodeiOS.cs
- features/fixtures/mazerunner/Assets/Scripts/Main.cs
- features/manual_spans.feature
- features/persistence.feature
- features/scene_load_spans.feature
- features/scripts/build_android.sh
- features/scripts/build_ios.sh
- features/scripts/build_macos.sh
- features/scripts/build_webgl.sh
- features/scripts/build_windows.sh
- features/scripts/run-macos-ci-tests.sh
- features/scripts/run-webgl-ci-tests.sh
- features/scripts/run-windows-ci-tests.sh
- features/steps/unity_steps.rb
- features/support/env.rb
Add windows build support for Unity Performance
- Added windows resource data
- Added e2e testing setup
Covered by existing tests
NOTE: the following tests are skipped due to flakyness that will be fixed in upcoming sprints:
scene_load_spans: Load Scene By Name, Load Scene By Index
persistence: P value response 0.0
> PLAT-10210 add windows support

- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Public/Span.cs
- CHANGELOG.md
- features/fixtures/mazerunner/Assets/Scripts/Scenarios/Network/ManualNetworkSpan.cs
- features/network_spans.feature
Status code was sent as a string attribute instead of an int
Updated E2E tests
> PLAT-11404 make sure status code is an int attribute

- .buildkite/pipeline.full.yml
- .buildkite/pipeline.yml
Install required gems on ci steps where they are needed.
Add `bundle install` to ci steps where needed.
Covered by CI
> [PLAT-11248] Add bundle install to pipeline file where needed.

- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Internal/SpanFactory.cs
- CHANGELOG.md
- features/fixtures/mazerunner/Assets/Scenes/MainScene.unity
- features/fixtures/mazerunner/Assets/Scripts/Scenarios/NestedSpans/IsFirstClass.cs
- features/fixtures/mazerunner/Assets/Scripts/Scenarios/NestedSpans/IsFirstClass.cs.meta
- features/nested_spans.feature
setting IsFirstClass = false was not respected in custom spans
Added E2E tests
> allow setting first class

- .buildkite/pipeline.full.yml
Move the full CI pipeline over to the macOs 14 boxes
Covered by CI
> Move full CI pipeline over to macos 14

- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Internal/SpanFactory.cs
- CHANGELOG.md
- features/manual_spans.feature
- features/persistence.feature
Fixed issue where the net.host.connection.type span attribute was not present in all spans 
Updated E2E tests
> PLAT-11350 add correct connection type to all span attributes

- features/fixtures/mazerunner/Assets/Scripts/Scenarios/NestedSpans/NewThreadNewContext.cs
- features/fixtures/mazerunner/ProjectSettings/ProjectSettings.asset
enable 64bit builds as default (will also produce 32 bit in the same apk)
> enable 64bit builds as default

- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Public/Span.cs
- features/rendering_metrics.feature
rendering span attributes were incorrectly named
> fix for rendering attributes naming

- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Internal/FrameMetricsCollector.cs
- features/fixtures/mazerunner/Assets/Scripts/Scenarios/Metrics/RenderMetrics.cs
- features/rendering_metrics.feature
add 5% tolerance to slow frame detection
Tightened up the tests to be more precise.
> add 5% tolerance to slow frame detection

- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Internal/FrameMetricsCollector.cs
- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Internal/Tracer.cs
- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Public/Span.cs
- BugsnagPerformance/Packages/manifest.json
- features/fixtures/mazerunner/Assets/Scripts/Scenarios/Metrics/RenderMetrics.cs
- features/rendering_metrics.feature
- features/steps/unity_steps.rb
Send a span with the category frozen_frame whenever one happens within a span tracking rendering metrics
Updated E2E tests
> Implement frozen frame spans

- BugsnagPerformance/Assets/BugsnagPerformance/Editor/BugsnagPerformanceEditor.cs
- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Internal/FrameMetricsCollector.cs
- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Internal/Tracer.cs
- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Public/BugsnagPerformanceSettingsObject.cs
- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Public/PerformanceConfiguration.cs
- features/fixtures/mazerunner/Assets/Scripts/Scenarios/Metrics/ConfigureRenderMetrics.cs
- features/fixtures/mazerunner/Assets/Scripts/Scenarios/Metrics/RenderMetrics.cs
Change to the EnabledMetrics config object instead of config. AutoInstrumentRendering
updated e2e tests
> implement EnableMetrics config object

- .buildkite/unity.2021.full.yml
- .buildkite/unity.2021.yml
- .github/ISSUE_TEMPLATE/A.md
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/SUPPORT.md
- .github/support.md
- SECURITY.md
Updates support docs with latest content and adds `SECURITY.md`.
> Automated adjustment of repository templates

- .buildkite/pipeline.yml
- BugsnagPerformance/Assets/BugsnagPerformance/Editor/PlayerSettingsCompat.cs
- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/BugsnagSceneManager/BugsnagSceneManager.cs
- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/BugsnagUnityWebRequest/BugsnagUnityWebRequest.cs
- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Internal/AppStartHandler.cs
- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Internal/BugsnagPerformanceAutoStart.cs
- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Internal/CacheManager.cs
- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Internal/Delivery.cs
- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Internal/PValueUpdater.cs
- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Internal/SpanFactory.cs
- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Internal/TracePayload.cs
- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Internal/Tracer.cs
- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Models/AttributeModel.cs
- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Public/BugsnagPerformance.cs
- BugsnagPerformance/Assets/Scripts/Main.cs
- BugsnagPerformance/Assets/UnitTests/TracePayloadTests.cs
- Rakefile
- scripts/code_format.sh
add code verification step to CI
> add code verification step to CI

- .buildkite/pipeline.yml
- .buildkite/unity.2020.full.yml
- .buildkite/unity.2021.full.yml
- .buildkite/unity.2021.yml
- .buildkite/unity.2022.full.yml
- .buildkite/unity.6000.full.yml
- Gemfile
Move CI tests to macos 14 isolated queue
Covered by CI
> [PLAt-14104] Move to isolated CI queue

- features/scripts/build_android.sh
- features/scripts/build_ios.sh
- features/scripts/build_macos.sh
- features/scripts/build_webgl.sh
- features/scripts/build_xcode_project.sh
- features/scripts/do_size_test.sh
- features/scripts/generate_xcode_project.sh
- features/scripts/import_package.sh
Ensure that when a build script fails, it fails the buildkite step with the correct status.
Covered by CI
> [PLAT-14148] Update build scripts

- .buildkite/pipeline.yml
- .buildkite/unity.2020.full.yml
- .buildkite/unity.2021.full.yml
- .buildkite/unity.2021.yml
- .buildkite/unity.2022.full.yml
- .buildkite/unity.6000.full.yml
Update the servers used for the CI steps so that we can properly test the Unity license server.
Covered by CI
> Update CI steps for license server testing

- BugsnagPerformance/Assets/BugsnagPerformance/Plugins/iOS/BugsnagPerformanceMetrics.mm
- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Native/iOSNative.cs
- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Public/PerformanceConfiguration.cs
- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Public/Span.cs
- BugsnagPerformance/Assets/Materials.meta
- BugsnagPerformance/Assets/Materials/Cube.mat
- BugsnagPerformance/Assets/Materials/Cube.mat.meta
- BugsnagPerformance/Assets/Scenes/Main.unity
- BugsnagPerformance/Assets/Scripts/Main.cs
- BugsnagPerformance/Assets/Scripts/Rotate.cs
- BugsnagPerformance/Assets/Scripts/Rotate.cs.meta
- features/cpu_metrics.feature
- features/fixtures/mazerunner/Assets/Scripts/Scenario.cs
- fix issues with iOS CPU metrics
- reduce batch timeout in dev builds and editor
- correct name for bugsnag.system.cpu_mean_total attribute
- add performance tools to dev project main scene
- ensure that the APIs used to attain metrics match those used in the native cocoa metrics collector
Covered by E2E tests
> Metrics uat fixes

- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Public/PerformanceConfiguration.cs
- BugsnagPerformance/Assets/UnitTests/ConfigurationTests.cs
- CHANGELOG.md
The hub endpoint was missing .otlp.
Updated unit tests
> add missing .otlp. to hub endpoint

- .buildkite/pipeline.full.yml
- .buildkite/unity.2020.full.yml
- .buildkite/unity.2021.full.yml
- .buildkite/unity.2021.yml
- .buildkite/unity.2022.full.yml
- .buildkite/unity.6000.full.yml
- features/dev.feature
- features/fixtures/mazerunner/Assets/Editor/Builder.cs
- features/fixtures/mazerunner/Assets/Scenes/MainScene.unity
- features/fixtures/mazerunner/Assets/Scripts/Scenarios/Dev.meta
- features/fixtures/mazerunner/Assets/Scripts/Scenarios/Dev/Dev.cs
- features/fixtures/mazerunner/Assets/Scripts/Scenarios/Dev/Dev.cs.meta
- features/scripts/run-macos-ci-tests.sh
- features/scripts/run-webgl-ci-tests.sh
- features/scripts/run-windows-ci-tests.sh
Added a new dev feature file with a smoke test for the shorter batch timeout and dev release stage
> enable dev build smoke tests
