bugsnag/bugsnag-unity-performance

- upm/upm-resources/README.md
- upm/upm-resources/README.md.meta
- upm/upm-resources/package.json.meta
Some assets in the performance upm package had guid conflicts with the notifier package. 
These are fixed now.
Also added a link to the public documentation in the package readme.
> fix guid errors and add public documentation

- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Public/BugsnagPerformanceSettingsObject.cs
when using the release stage and enabled release stages from the notifier config file, the perf sdk did not take into account that it should ignore empty values.
> fix shared release stage and enabled release stages

- example/Assets/Scenes/Example.unity
Fixes a typo in the example scene where a button was incorrectly named.
> Fix typo in example: scean -> scene

- features/fixtures/mazerunner/Assets/Scripts/Scenarios/Persistence/PValueRetry.cs
Repeate rate for p value requests was set too low and the initial request did not have time to finish.
> longer timeout to allow first request to process

- .buildkite/pipeline.full.yml
- .buildkite/pipeline.yml
- features/fixtures/mazerunner/Assets/Editor/Builder.cs
- features/fixtures/mazerunner/Assets/Editor/DisablingBitcodeiOS.cs
- features/fixtures/mazerunner/Assets/Editor/DisablingBitcodeiOS.cs.meta
- features/fixtures/mazerunner/Assets/Plugins/Android/AndroidManifest.xml
- features/steps/unity_steps.rb
Add unity 2022 builds to ci
- added required steps to pipeline
- updated fixtures to handle 2022 builds
- improved macos logging
covered by existing scenarios
> add unity 2022 to CI

- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Models/ResourceModel.cs
- CHANGELOG.md
- features/configuration.feature
- features/manual_spans.feature
the android version code and cocoa bundle version attributes had the incorrect keys
Updated tests to reflect the change
> PLAT-10777 fix mobile device version keys

- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Models/ResourceModel.cs
- features/configuration.feature
- features/manual_spans.feature
A gap in testing missed a bug where MacOS did not send a bundle version
Covered MacOS with existing ios bundle version e2e tests
> fix macos bundle version

- BugsnagPerformance/Assets/BugsnagPerformance/Plugins/MacOS/BugsnagUnityPerformanceMacOS.bundle.meta
- BugsnagPerformance/Assets/BugsnagPerformance/Plugins/MacOS/BugsnagUnityPerformanceMacOS.bundle/Contents.meta
- BugsnagPerformance/Assets/BugsnagPerformance/Plugins/MacOS/BugsnagUnityPerformanceMacOS.bundle/Contents/Info.plist.meta
- BugsnagPerformance/Assets/BugsnagPerformance/Plugins/MacOS/BugsnagUnityPerformanceMacOS.bundle/Contents/MacOS.meta
- BugsnagPerformance/Assets/BugsnagPerformance/Plugins/MacOS/BugsnagUnityPerformanceMacOS.bundle/Contents/MacOS/BugsnagUnityPerformanceMacOS.meta
- BugsnagPerformance/Assets/BugsnagPerformance/Plugins/MacOS/BugsnagUnityPerformanceMacOS.bundle/Contents/_CodeSignature.meta
- BugsnagPerformance/Assets/BugsnagPerformance/Plugins/MacOS/BugsnagUnityPerformanceMacOS.bundle/Contents/_CodeSignature/CodeResources.meta
- CHANGELOG.md
- CONTRIBUTING.md
Some versions of Unity see a macos bundle as a single file, but some see it as a directory and therefore require meta files for all files within the bundle in order to build correctly.
- added required meta files
Covered by existing tests
This SDK contains a MacOS bundle as a native plugin. Some versions of Unity (There seems to be no pattern, we have seen different behaviour in different patch versions of 2019 2020 & 2021) import that bundle as a single file, others import it as a folder. 
When importing as a single file it creates only 1 meta file, but when importing as a folder, it creates meta files for every file and folder within.
This causes a problem because we distribute the SDK as a UPM package. When importing a UPM package, Unity cannot create meta files on the fly, so if we …
> PLAT-10851 add macos plugin meta files

- Gemfile
- features/scripts/run-macos-ci-tests.sh
Use the latest version of Maze Runner for macOS tests.
Covered by a basic CI run.
> Use the latest version of Maze Runner for macOS tests

- .buildkite/pipeline.full.yml
- .buildkite/pipeline.yml
- features/scripts/run-macos-ci-tests.sh
- features/scripts/run-webgl-ci-tests.sh
- features/scripts/run-windows-ci-tests.sh
Save CI resources by failing a test run as soon as a 
Covered by a full CI run.
> E2e tests - fail fast

- BugsnagPerformance/Assets/BugsnagPerformance/Plugins/iOS/PrivacyInfo.xcprivacy
- BugsnagPerformance/Assets/BugsnagPerformance/Plugins/iOS/PrivacyInfo.xcprivacy.meta
- CHANGELOG.md
Add a privacy manifest to Plugins>iOS because we use the file creation timestamp as detailed here: https://docs.unity3d.com/2023.3/Documentation/Manual/apple-privacy-manifest-policy.html#CSharpDotNetAPIs
Manually tested that the file is present in a dry run release
> PLAT-11511 add apple privacy manifest

- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Models/ResourceModel.cs
- features/configuration.feature
I would like to fix a bug on Android that spans sent to the OLTP server are not registered.
Looking at [the SDK implementation for Android](https://github.com/bugsnag/bugsnag-android-performance/blob/b8e9e0ace2da570fb1ebeb6da0db254d0b3da7c3/bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/ResourceAttributes.kt#L20), it looks like using string type for `bugsnag.device.android_api_version` is the correct.
- Fix `bugsnag.device.android_api_version` attribute type int to string
- Fix a feature
I confirmed on [my forked repository](https://github.com/pobo380/bugsnag-unity-performance-upm/tree/fix-bugsnag-device-android-api) that this fix worked out and spans are registered correctly.
> fix `bugsnag.device.android_api_version` attribute type int to string

- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Internal/Version.cs
- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Models/ResourceModel.cs
- CHANGELOG.md
- Gemfile
- features/configuration.feature
- Fixed issue where the span attribute android_api_version was sent as a int attribute instead of a string [#99](https://github.com/bugsnag/bugsnag-unity-performance/pull/99)
> Release v1.3.2

- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Internal/BugsnagPerformanceAppLifecycleListener.cs
- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Internal/BugsnagPerformanceAppLifecycleListener.cs.meta
- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Internal/Tracer.cs
- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Public/BugsnagPerformance.cs
- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Public/Span.cs
- features/persistence.feature
discard open spans when app is backgrounded
Manually tested as there is no way to reliably backgroudn and then foreground a unity app
> PLAT-11880 discard open spans when app is backgrounded

- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Public/Span.cs
- CHANGELOG.md
- features/fixtures/mazerunner/Assets/Scenes/MainScene.unity
- features/fixtures/mazerunner/Assets/Scripts/Scenarios/Spans/CustomStartAndEndTime.cs
- features/fixtures/mazerunner/Assets/Scripts/Scenarios/Spans/CustomStartAndEndTime.cs.meta
- features/manual_spans.feature
allowing a custom span end time was overlooked in the original implementation.
Allow setting custom end time in the `Span.End()` and `Span.EndNetworkSpan()` methods
Added e2e tests
> allow custom span end time

- .gitignore
- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Internal/Sampler.cs
- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Internal/SpanFactory.cs
- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Public/BugsnagPerformance.cs
- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Public/PerformanceConfiguration.cs
- BugsnagPerformance/Assets/UnitTests/ConfigurationTests.cs
- CHANGELOG.md
- Gemfile
- docker-compose.yml
- features/fixtures/mazerunner/Assets/Scenes/MainScene.unity
- features/fixtures/mazerunner/Assets/Scripts/Scenarios/Network/TraceParentConfig.cs
- features/fixtures/mazerunner/Assets/Scripts/Scenarios/Network/TraceParentConfig.cs.meta
- features/fixtures/mazerunner/Assets/Scripts/Scenarios/Network/TraceParentHeaderSmokeTest.cs
- features/fixtures/mazerunner/Assets/Scripts/Scenarios/Network/TraceParentHeaderSmokeTest.cs.meta
- features/manual_spans.feature
- features/network_spans.feature
- features/scene_load_spans.feature
- features/scripts/run-webgl-ci-tests.sh
- features/steps/unity_steps.rb
- Add the trace parent header to requests made via the Bugsnag request wrapper.
- Allow configuration via `TracePropagationUrls`
Added E2E tests
> PLAT-12030 add trace parent header 

- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Internal/CacheManager.cs
- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Public/BugsnagPerformanceSettingsObject.cs
- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Public/PerformanceConfiguration.cs
- CHANGELOG.md
Keep notifier in line with notifier spec
boolean value in the configuration options which when set to false does not write, report or generate deviceId or persist to cache
- Added GenerateAnonymousId boolean option to config
- Edited the CacheManager.cs GetDeviceId to check the value of config GenerateAnonymousId value
Tested manually by setting to true and sending spans - which reported spans with device ID.
Then set to false and sent spans - which reported spans with no device ID
> Plat 10311 add generate anonymous id value

- features/fixtures/mazerunner/Packages/manifest.json
Add the Bugsnag Unity Notifier to the performance test fixture.
This is to pave the way for testing interconnected features and to test that both SDKs can be imported without issue.
Successful build of the fixture prooves no import conflicts or resulting issues
> add notifier to fixture [full ci]

- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Public/BugsnagPerformance.cs
This PR is part of work connected to the Unity Notifier, the sister PR can be found here: https://github.com/bugsnag/bugsnag-unity/pull/801
Please do not review this PR without also reviewing the other
Provide access to the unity notifier so that when a C# layer error occurs, it can get the current span context and include it in the event report.
Added GetPerformanceState method in BugsnagPerformance that can be accessed via reflection.
Manually tested
E2E Tests will be added in a later task
> PLAT-12127 add traceid to error events

- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Internal/SpanFactory.cs
- CHANGELOG.md
Calling Application.internetReachability from a background thread is not allowed and throws an exception.
NOTE: This bug was not caught by our E2E testing because IL2CPP strips out the thread safety check in release builds.
Changed to a polling method that checks the connection status once a second.
Covered by existing E2E tests
> PLAT-12235 fix for connection type check on main thread

- .gitignore
- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Internal/SpanFactory.cs
- CHANGELOG.md
- features/fixtures/mazerunner/Assets/Scenes/MainScene.unity
- features/fixtures/mazerunner/Assets/Scripts/Scenarios/NestedSpans/PassContextWithMakeContextFalse.cs
- features/fixtures/mazerunner/Assets/Scripts/Scenarios/NestedSpans/PassContextWithMakeContextFalse.cs.meta
- features/nested_spans.feature
Fix a bug where if a span with MakeCurrentContext set to false was passed as a parent then it would be added to the context stack
Now spans passed as parents will only be assigned as the parent for that particular span.
Added a new E2E test to cover this scenario
> PLAT-12362 fix issue with span parentage when MakeCurrentContext is false

- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Public/BugsnagPerformance.cs
- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Public/PerformanceConfiguration.cs
- BugsnagPerformance/Assets/UnitTests/ConfigurationTests.cs
- CHANGELOG.md
- features/fixtures/mazerunner/Assets/Scripts/Scenarios/Network/TraceParentConfig.cs
The config value `TracePropagationUrls` was incorrectly named and typed.
It should be a Regex Pattern collection.
Added unit test and covered by existing E2E tests
> PLAT-12568 correct TracePropagationUrls

- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Internal/Sampler.cs
- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Internal/SpanFactory.cs
- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Internal/Tracer.cs
- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Public/BugsnagPerformance.cs
- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Public/Span.cs
- CHANGELOG.md
- features/correlation.feature
- features/fixtures/mazerunner/Assets/Scripts/Scenarios/Configuration/CustomReleaseStage.cs
- features/fixtures/mazerunner/Assets/Scripts/Scenarios/Configuration/DisabledReleaseStages.cs
- features/fixtures/mazerunner/Assets/Scripts/Scenarios/Configuration/EmptyReleaseStages.cs
- features/fixtures/mazerunner/Assets/Scripts/Scenarios/Configuration/EnabledReleaseStages.cs
- features/fixtures/mazerunner/Assets/Scripts/Scenarios/Correlation/CorrelationOnDifferentThread.cs
- features/fixtures/mazerunner/Assets/Scripts/Scenarios/Network/ManualNetworkSpan.cs
- features/fixtures/mazerunner/Assets/Scripts/Scenarios/Persistence/PValueUpdate.cs
- features/fixtures/mazerunner/Assets/Scripts/Scenarios/SceneLoad/ManualSceneSpan.cs
- features/fixtures/mazerunner/Assets/Scripts/Scenarios/Spans/ConfiguredSamplingRate0.cs
- features/fixtures/mazerunner/Assets/Scripts/Scenarios/Spans/ConfiguredSamplingRate1.cs
- features/fixtures/mazerunner/Assets/Scripts/Scenarios/Spans/ManualSpan.cs
Convert span refs to weak refs to avoid memory leaks
- Convert the context stack in `SpanFactory.cs` to `Stack<WeakReference<ISpanContext>>`
- Convert `_preStartSpans` and `_finishedSpanQueue` in `Tracer.cs` to `Stack<WeakReference<ISpanContext>>`
- Fix bug in `Tracer.cs` where `OnEndCallbacks` ran twice on pre start spans
- Convert pending network spans collection to `Dictionary<WeakReference<BugsnagUnityWebRequest>, Span>`
- Converted multiple E2E tests that used time based batches to use batchsize instead to avoid race conditions
- Some code formatting refactor
Now that the collection BugsnagPerformance._potentiallyOpenSpans is a weak reference collection, it's no longer important to remove spans from it when they are ended. Because of this it is also no longer necessary to call the …
> PLAT-10952 convert span refs to weak refs to avoid memory leaks

- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Internal/Delivery.cs
- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Internal/PValueUpdater.cs
- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Internal/Sampler.cs
- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Internal/TracePayload.cs
- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Public/BugsnagPerformance.cs
- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Public/PerformanceConfiguration.cs
- BugsnagPerformance/Assets/UnitTests/ConfigurationTests.cs
- BugsnagPerformance/Assets/UnitTests/SamplerTests.cs
- BugsnagPerformance/Assets/UnitTests/TracePayloadTests.cs
- CHANGELOG.md
- Gemfile
- features/fixtures/mazerunner/Assets/Scenes/MainScene.unity
- features/fixtures/mazerunner/Assets/Scripts/Scenario.cs
- features/fixtures/mazerunner/Assets/Scripts/Scenarios/Sampling.meta
- features/fixtures/mazerunner/Assets/Scripts/Scenarios/Sampling/OverrideSampling0.cs
- features/fixtures/mazerunner/Assets/Scripts/Scenarios/Sampling/OverrideSampling0.cs.meta
- features/fixtures/mazerunner/Assets/Scripts/Scenarios/Sampling/OverrideSampling1.cs
- features/fixtures/mazerunner/Assets/Scripts/Scenarios/Sampling/OverrideSampling1.cs.meta
- features/fixtures/mazerunner/Assets/Scripts/Scenarios/Spans/ConfiguredSamplingRate0.cs
- features/fixtures/mazerunner/Assets/Scripts/Scenarios/Spans/ConfiguredSamplingRate1.cs
- features/sampling.feature
Expose `SamplingProbability`, unset by default, causing the SDK to use the current dynamic sampling logic
If set:
- disable the initial and periodic p-value requests being sent
- disable the setting of the Bugsnag-Span-Sampling header
- keep the bugsnag.sampling.p attribute for possible future use
Updated unit tests and E2E tests
> PLAT-12557 add a fixed sampling probability configuration option

- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Internal/Delivery.cs
- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Public/BugsnagPerformanceSettingsObject.cs
- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Public/PerformanceConfiguration.cs
- BugsnagPerformance/Assets/UnitTests/ConfigurationTests.cs
- CHANGELOG.md
use API key subdomain as endpoint
The original default endpoint must be checked against because if someone was using the bugsnag config window and the default endpoint and then updates to the new release, then it will be read from the config file anyway and override the new default.
Added unit tests
> PLAT-12447 use API key subdomain as endpoint

- BugsnagPerformance/Assets/BugsnagPerformance/Editor/BugsnagPerformanceEditor.cs
- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Models/ResourceModel.cs
- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Public/BugsnagPerformanceSettingsObject.cs
- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Public/PerformanceConfiguration.cs
- CHANGELOG.md
- features/configuration.feature
- features/fixtures/mazerunner/Assets/Scenes/MainScene.unity
- features/fixtures/mazerunner/Assets/Scripts/Scenarios/Configuration/CustomServiceName.cs
- features/fixtures/mazerunner/Assets/Scripts/Scenarios/Configuration/CustomServiceName.cs.meta
- features/manual_spans.feature
send the app identifier (e.g. com.mycorp.myapp) in the service.name attribute.
- If the config value is not set then we use the [application identifier](https://docs.unity3d.com/ScriptReference/Application-identifier.html). If that is empty then we use [product name](https://docs.unity3d.com/ScriptReference/Application-productName.html). If that is also empty then we report `unknown_service `. 
Added E2E tests for custom and default service names
> PLAT-12051 add service.name attribute

- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Internal/Tracer.cs
- CHANGELOG.md
When building a batch, the access to the finished span queue in the tracer class is not thread safe.
Manually stress tested as mazerunner cannot handle so many traces at once.
> PLAT-12684 make finished span queue thread safe

- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Internal/Tracer.cs
- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Internal/Version.cs
- CHANGELOG.md
- Fix an issue where the access to the finished span queue in the tracer was not thread safe. [#132](https://github.com/bugsnag/bugsnag-unity-performance/pull/132)
> Release v1.5.1

- Gemfile
Use the latest v9 Maze Runner (when running locally).
This change means you get the latest v9.something, not just v9.13.something.
Basic test performed locally by running `bundle install`.
> Use the latest v9 Maze Runner

- BugsnagPerformance/Assets/BugsnagPerformance/Editor/BugsnagPerformanceEditor.cs
- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Public/BugsnagPerformanceSettingsObject.cs
- CHANGELOG.md
Add `TracePropagationUrls` to the configuration window.
- TracePropagationUrls is presented as a string[] in the window.
- On start the strings are converted. 
- If a conversion fails then we skip the offending string and log a warning message.
Manually tested
> add TracePropagationUrls to the configuration window

- features/fixtures/mazerunner/Assets/Scripts/Scenarios/Spans/ConfiguredSamplingRate1.cs
Fix flaky test where the spans were ending before the initial sampling request was finished
> fix flaky webgl sampling test

- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Models/SpanModel.cs
- CHANGELOG.md
- features/custom_attributes.feature
- features/manual_spans.feature
dropped attribute count was incorrectly implemented, it is now a top level property of a span and named with cammel case.
Updated e2e tests
> rename and move dropped attribute count to correct place

- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Internal/PValueUpdater.cs
- CHANGELOG.md
The SDK uses DateTimeOffset.UtcNow at all times, but the P Value updater was mistakenly using local time which can cause app hangs on iOS.
Covered by existing tests
> change pvalue update to use DateTimeOffset.UtcNow

- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/BugsnagPerformance.asmdef
- CHANGELOG.md
The latest Bugsnag Unity Notifier release [v8.3.0](https://github.com/bugsnag/bugsnag-unity/releases/tag/v8.3.0) broke the ability of the performance SDK to share the UnityWebRequest Wrapper as it now uses an assembly definition.
Added a reference to the new BugsnagUnity assembly defenition in the performance assembly definition. If the notifier is not present then it ignores to included reference.
Full e2e and manually tested locally
> fix for missing assembly reference

- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/BugsnagPerformance.asmdef
- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Internal/Version.cs
- CHANGELOG.md
- features/fixtures/mazerunner/Assets/Scripts/Scenarios/Network/NetworkPostFail.cs
- features/fixtures/mazerunner/Assets/Scripts/Scenarios/Network/NetworkPostSuccess.cs
- Fix an issue where using this SDK with v8.3.0+ of the BugSnag Unity Notifier would cause an exception while trying to resolve the BugsnagUnityWebRequest wrapper [#151](https://github.com/bugsnag/bugsnag-unity-performance/pull/151)
> Release v1.7.1

- .gitignore
- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Public/Span.cs
- CHANGELOG.md
- features/fixtures/mazerunner/Assets/Scenes/MainScene.unity
- features/fixtures/mazerunner/Assets/Scripts/Scenarios/Spans/NullSpanName.cs
- features/fixtures/mazerunner/Assets/Scripts/Scenarios/Spans/NullSpanName.cs.meta
- features/manual_spans.feature
Span names in custom spans were not null checked and so the sdk was reporting spans with no name field. 
Now we check and set the name to an empty string.
Added new E2E test
> send string.Empty if span name is null

- BugsnagPerformance/Assets/BugsnagPerformance/Editor/BugsnagPerformanceEditor.cs
- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Internal/FrameMetricsCollector.cs
- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Internal/FrameMetricsCollector.cs.meta
- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Internal/SpanFactory.cs
- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Internal/Tracer.cs
- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Native/AndroidNative.cs
- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Public/BugsnagPerformance.cs
- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Public/BugsnagPerformanceSettingsObject.cs
- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Public/PerformanceConfiguration.cs
- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Public/Span.cs
- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Public/SpanOptions.cs
- BugsnagPerformance/Assets/Scripts/Main.cs
- BugsnagPerformance/Assets/UnitTests/ConfigurationTests.cs
- BugsnagPerformance/Assets/UnitTests/SamplerTests.cs
- BugsnagPerformance/Assets/UnitTests/TracePayloadTests.cs
- CHANGELOG.md
- features/fixtures/mazerunner/Assets/Scenes/MainScene.unity
- features/fixtures/mazerunner/Assets/Scripts/Scenarios/Metrics/ConfigureRenderMetrics.cs
- features/fixtures/mazerunner/Assets/Scripts/Scenarios/Metrics/ConfigureRenderMetrics.cs.meta
- features/fixtures/mazerunner/Assets/Scripts/Scenarios/Metrics/RenderMetrics.cs
- features/fixtures/mazerunner/Assets/Scripts/Scenarios/Metrics/RenderMetrics.cs.meta
- features/rendering_metrics.feature
add frame rate metrics to custom first class spans and automatic navigation, network and app start spans.
Added FrameMetricsCollector that hooks into the unity update call. This is called once per frame and checks Time.unscaledDeltaTime to decide what category of frame has just happened.
Added check to remove metrics added to spans before start is called if rendering metrics are not enabled in config.
Added new config option to the config window.
Added new E2E tests
> add frame rate metrics

- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Internal/FrameMetricsCollector.cs
Update the frame-timing logic to use real clock timestamps for measuring frozen frames. By replacing Time.unscaledDeltaTime-based calculations with explicit timestamps, we ensure consecutive frozen frames no longer have overlapping start/end times. We also incorporate our existing slow-frame logic into the same code path, so we capture both frozen and slow frames accurately.
Covered by existing E2E tests
> Frozen frame overlap fix

- Rakefile
set UPM package version when building on CI so that we can release the same package artifact we test with.
- Updated Rake method
Manually tested
> set UPM package version when building on CI

- BugsnagPerformance/Assets/BugsnagPerformance/Editor/AddScriptingSymbol.cs
- BugsnagPerformance/Assets/BugsnagPerformance/Editor/PlayerSettingsCompat.cs
- BugsnagPerformance/Assets/BugsnagPerformance/Editor/PlayerSettingsCompat.cs.meta
- CHANGELOG.md
Add a PlayerSettingsCompat class to handle changes in the Unity PlayerSettings API.
Fix a bug where when running in batch mode could remove all scripting symbols.
Covered by existing E2E tests. Will also have extra coverage once released as this fix will allow for the performance sdk to be present in the notifier fixture.
> improve scripting symbol addition and handle unity deprecations 

- features/steps/unity_steps.rb
Change the e2e tests to use the new Maze Runner Appium API, meaning that we detect and report driver failures.
A Cucumber step definition has been removed as it's not used in this repo.
Covered by CI.
> Don't use Maze.driver directly

- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Internal/FrameMetricsCollector.cs
- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Internal/SpanFactory.cs
- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Internal/Tracer.cs
- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Models/ResourceModel.cs
- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Public/Span.cs
- BugsnagPerformance/Assets/UnitTests/ConfigurationTests.cs
- BugsnagPerformance/Assets/UnitTests/SamplerTests.cs
- BugsnagPerformance/Assets/UnitTests/TracePayloadTests.cs
- features/manual_spans.feature
- features/rendering_metrics.feature
add the following new span attributes:
```
bugsnag.rendering.fps_target
bugsnag.rendering.fps_average
bugsnag.rendering.fps_minimum
bugsnag.rendering.fps_maximum
```
add the following new resource attributes:
```
device.screen_resolution.width
device.screen_resolution.height
```
- register eligible spans in the FrameMetricsCollector on collection.
- apply collected metrics on span end
- add screen res attribute in the Resource Model class
Updated existing tests with the new attributes
> add basic fps rendering metrics

- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Internal/AppStartHandler.cs
- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Internal/SpanFactory.cs
- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Public/SpanOptions.cs
- CHANGELOG.md
- features/app_start_spans.feature
- features/fixtures/mazerunner/Assets/Scripts/Scenarios/Metrics/RenderMetrics.cs
- features/network_spans.feature
- features/scene_load_spans.feature
- features/steps/unity_steps.rb
This PR is the ground work required before adding the csharp layer of CPU/Memory metrics.
The goal is to implement span metrics object and remove `SpanOptions.InstrumentRendering`
- remove `SpanOptions.InstrumentRendering`
- implement `SpanMetrics` object.
- Refactor App starts to use const keys and set the correct First Class attribute.
- Refactor `SpanFactory` so that the reading and setting of IsFirstClass is easier to understand.
- Updated existing tests to check for IsFirst class when relevant.
> implement span metrics object

- .buildkite/pipeline.yml
- .buildkite/unity.2020.full.yml
- .buildkite/unity.2021.full.yml
- .buildkite/unity.2021.yml
- .buildkite/unity.2022.full.yml
- .buildkite/unity.6000.full.yml
Bump the versions of Unity installs to match what is installed on the box.
Move everything but E2E tests to the general queue
Covered by CI
> [PLAT-14104] Update Unity Performance CI Queues

- .buildkite/pipeline.yml
- .buildkite/unity.2020.full.yml
- .buildkite/unity.2021.full.yml
- .buildkite/unity.2021.yml
- .buildkite/unity.2022.full.yml
- .buildkite/unity.6000.full.yml
- BugsnagPerformance/Assets/BugsnagPerformance/Plugins/iOS/BugsnagPerformanceMetrics.mm
- BugsnagPerformance/Assets/BugsnagPerformance/Plugins/iOS/BugsnagPerformanceMetrics.mm.meta
- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Internal/SystemMetricsCollector.cs
- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Internal/Tracer.cs
- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Native/iOSNative.cs
- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Public/Span.cs
- features/cpu_metrics.feature
- features/memory_metrics.feature
Add native memory and CPU metrics for unity iOS builds.
- Added native iOS calls to sample memory and CPU stats, see `BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Native/iOSNative.cs` and `BugsnagPerformance/Assets/BugsnagPerformance/Plugins/iOS/BugsnagPerformanceMetrics.mm.`
- Moved span processing delay to happen after sampling to allow more time for app start spans to have metrics.
Create iOS specific tests
> add cocoa system metrics

- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Public/PerformanceConfiguration.cs
- BugsnagPerformance/Assets/UnitTests/ConfigurationTests.cs
- CHANGELOG.md
Set default endpoints based on API key. If no endpoint is configured, payloads should be sent to `*.insighthub.smartbear.com` if the API key starts with `00000`.
- Refactored PerformanceConfiguration class to support hub endpoints
Unit tested
> Set default endpoints based on API key

- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Internal/FrameMetricsCollector.cs
- BugsnagPerformance/Assets/BugsnagPerformance/Scripts/Public/Span.cs
- BugsnagPerformance/Assets/UnitTests/SpanTests.cs
- BugsnagPerformance/Assets/UnitTests/SpanTests.cs.meta
- CHANGELOG.md
we shouldn’t send CPU metrics if there is no cpu_mean_total due to it being unavailable on the device
- check for valid CPU data when applying CPU metrics to a span, if not valid don't add the data.
Added new Span unit tests
> don't send CPU data if cpu_mean_total is not available
